import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import * as Location from 'expo-location';
import MapView, { Marker, type MapPressEvent } from 'react-native-maps';

import type { LocationPickerProps } from './LocationPicker.types';
import { AppIcon } from '@/components/shared/AppIcon';
import { Body, Label } from '@/components/shared/Typography';
import { colors, radius } from '@/constants/theme';
import { reverseLocation, searchLocations } from '@/services/martnow';
import type { StoreLocationResult } from '@/types/api';
import { getErrorMessage } from '@/utils/error-message';

const DEFAULT = { latitude: 30.3753, longitude: 69.3451, latitudeDelta: 8, longitudeDelta: 8 };
const coordinate = (value: string) => Number.isFinite(Number(value)) ? Number(value) : null;
const format = (value: number) => String(Math.round(value * 10_000_000) / 10_000_000);

export default function LocationPicker({ value, onChange, error, label = 'Complete delivery address' }: LocationPickerProps) {
  const [query, setQuery] = useState(value.address); const [results, setResults] = useState<StoreLocationResult[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const latitude = coordinate(value.latitude); const longitude = coordinate(value.longitude); const region = useMemo(() => latitude != null && longitude != null ? { latitude, longitude, latitudeDelta: 0.012, longitudeDelta: 0.012 } : DEFAULT, [latitude, longitude]);
  const select = (location: StoreLocationResult) => { setQuery(location.address); setResults([]); setMessage('Location selected.'); onChange({ address: location.address, latitude: format(location.latitude), longitude: format(location.longitude) }); };
  const search = async () => { if (query.trim().length < 3) { setMessage('Enter at least 3 characters.'); return; } setBusy(true); setMessage(''); try { const rows = await searchLocations(query.trim()); setResults(rows); setMessage(rows.length ? 'Select the correct result.' : 'No matching location found.'); } catch (cause) { setMessage(getErrorMessage(cause)); } finally { setBusy(false); } };
  const current = async () => { setBusy(true); setMessage(''); try { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) { setMessage('Location permission is required to use your current position.'); return; } const position = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); select(await reverseLocation(position.coords.latitude, position.coords.longitude)); } catch (cause) { setMessage(getErrorMessage(cause)); } finally { setBusy(false); } };
  const pick = async (event: MapPressEvent) => { const { latitude: nextLat, longitude: nextLng } = event.nativeEvent.coordinate; onChange({ ...value, latitude: format(nextLat), longitude: format(nextLng) }); setBusy(true); try { select(await reverseLocation(nextLat, nextLng)); } catch { setMessage('Pin saved. You can type the complete address manually.'); setBusy(false); } finally { setBusy(false); } };
  return <View style={styles.root}><Label style={styles.label}>{label}</Label><View style={[styles.search, error && styles.errorBorder]}><AppIcon name="search-outline" size={18} color={colors.teal} /><TextInput value={query} onChangeText={(text) => { setQuery(text); onChange({ ...value, address: text }); setResults([]); }} placeholder="Search area, road, city or landmark" placeholderTextColor="#71817B" style={styles.input} onSubmitEditing={() => { void search(); }} /><Pressable disabled={busy} onPress={() => { void search(); }} style={styles.searchButton}><Label style={styles.searchButtonText}>{busy ? '…' : 'Search'}</Label></Pressable></View>{error ? <Body style={styles.error}>{error}</Body> : null}{results.length ? <View style={styles.results}>{results.map((item) => <Pressable key={`${item.latitude}-${item.longitude}`} onPress={() => select(item)} style={({ pressed }) => [styles.result, pressed && styles.pressed]}><AppIcon name="location-outline" size={17} color={colors.teal} /><Body style={styles.resultText}>{item.address}</Body></Pressable>)}</View> : null}<View style={styles.actionRow}><Pressable disabled={busy} onPress={() => { void current(); }} style={({ pressed }) => [styles.locationButton, pressed && styles.pressed, busy && styles.disabled]}><AppIcon name="locate-outline" size={17} color={colors.teal} /><Label style={styles.locationText}>Use current location</Label></Pressable><Body style={styles.hint}>Or tap the map to place a pin.</Body></View><MapView key={`${region.latitude}-${region.longitude}`} initialRegion={region} onPress={(event) => { void pick(event); }} style={styles.map}>{latitude != null && longitude != null ? <Marker coordinate={{ latitude, longitude }} draggable onDragEnd={(event) => { void pick(event as MapPressEvent); }} /> : null}</MapView><View style={styles.coords}><Body style={styles.coord}>Lat: {latitude ?? 'Not set'}</Body><Body style={styles.coord}>Lng: {longitude ?? 'Not set'}</Body></View>{message ? <Body style={styles.message}>{message}</Body> : null}</View>;
}

const styles = StyleSheet.create({ root: { gap: 8 }, label: { fontSize: 13 }, search: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, overflow: 'hidden' }, input: { minWidth: 0, flex: 1, minHeight: 48, color: colors.ink, fontFamily: 'Outfit_400Regular', fontSize: 13 }, searchButton: { alignSelf: 'stretch', justifyContent: 'center', paddingHorizontal: 12, backgroundColor: colors.teal }, searchButtonText: { color: '#fff', fontSize: 11 }, results: { overflow: 'hidden', borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, result: { flexDirection: 'row', gap: 8, padding: 11, borderBottomWidth: 1, borderBottomColor: '#EDF2F0' }, resultText: { flex: 1, fontSize: 12, lineHeight: 17 }, actionRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8 }, locationButton: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11, borderRadius: 11, backgroundColor: colors.tealSoft }, locationText: { color: colors.teal, fontSize: 11 }, hint: { fontSize: 10 }, map: { width: '100%', height: 230, borderRadius: radius.md }, coords: { flexDirection: 'row', justifyContent: 'space-between' }, coord: { fontSize: 10 }, message: { fontSize: 11, lineHeight: 16 }, error: { color: colors.danger, fontSize: 11 }, errorBorder: { borderColor: colors.danger }, pressed: { opacity: 0.65 }, disabled: { opacity: 0.45 } });
