import { useState } from 'react';
import { Linking, Pressable, StyleSheet, TextInput, View } from 'react-native';

import type { LocationPickerProps } from './LocationPicker.types';
import { AppIcon } from '@/components/shared/AppIcon';
import { Body, Label } from '@/components/shared/Typography';
import { colors, radius } from '@/constants/theme';
import { reverseLocation, searchLocations } from '@/services/martnow';
import type { StoreLocationResult } from '@/types/api';
import { getErrorMessage } from '@/utils/error-message';

const format = (value: number) => String(Math.round(value * 10_000_000) / 10_000_000);

export default function LocationPicker({ value, onChange, error, label = 'Complete delivery address' }: LocationPickerProps) {
  const [query, setQuery] = useState(value.address); const [results, setResults] = useState<StoreLocationResult[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const select = (item: StoreLocationResult) => { setQuery(item.address); setResults([]); onChange({ address: item.address, latitude: format(item.latitude), longitude: format(item.longitude) }); setMessage('Location selected.'); };
  const search = async () => { if (query.trim().length < 3) { setMessage('Enter at least 3 characters.'); return; } setBusy(true); try { const rows = await searchLocations(query.trim()); setResults(rows); setMessage(rows.length ? 'Select the correct result.' : 'No matching location found.'); } catch (cause) { setMessage(getErrorMessage(cause)); } finally { setBusy(false); } };
  const current = () => { if (typeof navigator === 'undefined' || !navigator.geolocation) { setMessage('Location is not supported by this browser.'); return; } setBusy(true); navigator.geolocation.getCurrentPosition((position) => { void reverseLocation(position.coords.latitude, position.coords.longitude).then(select).catch((cause) => setMessage(getErrorMessage(cause))).finally(() => setBusy(false)); }, (cause) => { setBusy(false); setMessage(cause.message); }, { enableHighAccuracy: true, timeout: 10000 }); };
  const mapUrl = value.latitude && value.longitude ? `https://www.openstreetmap.org/?mlat=${value.latitude}&mlon=${value.longitude}#map=17/${value.latitude}/${value.longitude}` : '';
  return <View style={styles.root}><Label style={styles.label}>{label}</Label><View style={[styles.search, error && styles.errorBorder]}><AppIcon name="search-outline" size={18} color={colors.teal} /><TextInput value={query} onChangeText={(text) => { setQuery(text); onChange({ ...value, address: text }); setResults([]); }} placeholder="Search area, road, city or landmark" placeholderTextColor="#71817B" style={styles.input} onSubmitEditing={() => { void search(); }} /><Pressable disabled={busy} onPress={() => { void search(); }} style={styles.searchButton}><Label style={styles.searchButtonText}>{busy ? '…' : 'Search'}</Label></Pressable></View>{error ? <Body style={styles.error}>{error}</Body> : null}{results.length ? <View style={styles.results}>{results.map((item) => <Pressable key={`${item.latitude}-${item.longitude}`} onPress={() => select(item)} style={styles.result}><AppIcon name="location-outline" size={17} color={colors.teal} /><Body style={styles.resultText}>{item.address}</Body></Pressable>)}</View> : null}<View style={styles.actions}><Pressable disabled={busy} onPress={current} style={styles.button}><AppIcon name="locate-outline" size={17} color={colors.teal} /><Label style={styles.buttonText}>Use current location</Label></Pressable>{mapUrl ? <Pressable onPress={() => { void Linking.openURL(mapUrl); }} style={styles.button}><AppIcon name="map-outline" size={17} color={colors.teal} /><Label style={styles.buttonText}>Open selected pin</Label></Pressable> : null}</View><View style={styles.mapFallback}><AppIcon name="map-outline" size={30} color={colors.teal} /><Body style={styles.mapText}>{mapUrl ? 'Selected map coordinates are saved.' : 'Search or use your location to set the delivery pin.'}</Body></View>{message ? <Body style={styles.message}>{message}</Body> : null}</View>;
}

const styles = StyleSheet.create({ root: { gap: 8 }, label: { fontSize: 13 }, search: { minHeight: 50, flexDirection: 'row', alignItems: 'center', gap: 8, paddingLeft: 12, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, overflow: 'hidden' }, input: { minWidth: 0, flex: 1, minHeight: 48, color: colors.ink, fontFamily: 'Outfit_400Regular', fontSize: 13 }, searchButton: { alignSelf: 'stretch', justifyContent: 'center', paddingHorizontal: 12, backgroundColor: colors.teal }, searchButtonText: { color: '#fff', fontSize: 11 }, results: { overflow: 'hidden', borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, result: { flexDirection: 'row', gap: 8, padding: 11, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: '#EDF2F0' }, resultText: { flex: 1, fontSize: 12 }, actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, button: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11, borderRadius: 11, backgroundColor: colors.tealSoft }, buttonText: { color: colors.teal, fontSize: 11 }, mapFallback: { minHeight: 150, alignItems: 'center', justifyContent: 'center', gap: 8, padding: 20, borderRadius: radius.md, borderWidth: 1, borderStyle: 'dashed', borderColor: colors.border, backgroundColor: '#F6FAF8' }, mapText: { textAlign: 'center', fontSize: 12 }, message: { fontSize: 11 }, error: { color: colors.danger, fontSize: 11 }, errorBorder: { borderColor: colors.danger } });
